services:
  api:
    image: nullpdev/telemetry-api:latest
    container_name: telemetry-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DB_URL}
      - TELEMETRY_API_KEY=${TELEMETRY_API_KEY}
    restart: unless-stopped

  prometheus:
    image: nullpdev/telemetry-prometheus:latest
    container_name: telemetry-prometheus
    volumes:
      - prom_data:/prometheus
    restart: unless-stopped

  grafana:
    image: nullpdev/telemetry-grafana:latest
    container_name: telemetry-grafana
    ports:
      - "80:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

  postgres-exporter:
    image: nullpdev/telemetry-postgres-exporter:latest
    container_name: telemetry-postgres-exporter
    environment:
      - DATA_SOURCE_NAME=${EXPORTER_DB_URL}
    restart: unless-stopped

volumes:
  prom_data:
  grafana_data: