apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://telemetry-prometheus:9090
    isDefault: true
    uid: prometheus
    editable: false

  - name: PostgreSQL_Telemetry
    type: postgres
    uid: postgresql_telemetry
    access: proxy
    url: telemetry-db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: telemetry_db
      sslmode: 'disable'
      postgresVersion: 1800
    editable: false