apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    uid: prometheus
    editable: false

  - name: PostgreSQL_Telemetry
    type: postgres
    uid: postgresql_telemetry
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DATABASE}
      sslmode: '${POSTGRES_SSLMODE}'
      postgresVersion: 1800
    editable: false