CREATE TABLE telemetry
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    hostname VARCHAR(100) NOT NULL,
    cpu_usage_percentage DOUBLE PRECISION NOT NULL,
    memory_total_mb DOUBLE PRECISION NOT NULL,
    memory_used_mb DOUBLE PRECISION NOT NULL,
    disk_total_gb DOUBLE PRECISION NOT NULL,
    disk_used_gb DOUBLE PRECISION NOT NULL,
    system_uptime_seconds BIGINT NOT NULL,
    captured_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_telemetry PRIMARY KEY (id)
);
