name: telemetry-api

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'build.gradle*'
      - 'settings.gradle*'
      - 'gradle/**'
      - 'Dockerfile'
      - '.github/workflows/telemetry-api.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build application with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-api:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Render deploy
        env:
          HOOK: ${{ secrets.RENDER_HOOK_API }}
        run: |
            curl -fsS "${HOOK}&imgURL=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/telemetry-api:${{ github.sha }}"